// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hikuxbxvfbymbaepoiqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhpa3V4Ynh2ZmJ5bWJhZXBvaXFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzQyODYsImV4cCI6MjA3MjU1MDI4Nn0.kclwss6lyWBICialLY1wA_hFc2Oq0fa6qLa8peSfYpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});